---
title: "HW 3: dplyr"
author: John Ahn
output: html_document
---
### SETUP
```{r}

library(babynames)
library(tidyverse)
library(gapminder)

babynames
```

### 1. Dplyr
#### (1-a)
```{r}
babynames %>% 
  filter(year == 2017, sex == "F" ) %>%
  arrange(desc(n))
```
```{r}
# Emma is the most common name 
```


#### (1-b)
```{r}
babynames %>%
  filter(year == 1982) %>%
  mutate(counter = 1 ) %>%
  group_by(sex) %>%
  summarize(n = sum(counter))
```

```{r}
# For the year 1982, the number of males was 7364
```

#### (1-c)
```{r}
babynames %>%
  mutate(counter = 1) %>%
  group_by(year, sex) %>%
  summarize(n = sum(counter))
```

### 2. Dplyr + qplot
#### (2-a)

```{r}
babynames %>%
  filter(year == 2017) %>%
  arrange(desc(n))
```

```{r}
vectortop_names_2017 <- babynames %>%
  filter(name %in% c("Emma", "Liam", "Olivia", "Noah"))
```

#### (2-b)
```{r}
ggplot(vectortop_names_2017, aes(x = year, y = prop)) +
  geom_line(aes(color = name))
```


#### (2-c)
```{r}
vectortop_names_2017 <- babynames %>%
  filter(name %in% c("Emma", "Liam", "Olivia", "Noah"), prop > 0.0002)

ggplot(vectortop_names_2017, aes(x = year, y = prop)) +
  geom_line(aes(color = name))

```



```{r}
library(gapminder)
gapminder[[5]]
```

```{r}
library(tidyverse)
midwest[4:8, 2:4]
```

